services:

  subtrace:
    build:
      context: ./
      dockerfile: alpine.Dockerfile
    container_name: subtrace
#    image: subtrace/server:latest
    labels:
      description: Wireshark for Docker containers
      name: SubtraceService
    restart: unless-stopped    
    ports:
      - "8080:8080"  # Веб-интерфейс Subtrace
      - "4317:4317"  # OTLP (OpenTelemetry)
    environment:
      - SUBTRACE_STORAGE_TYPE=memory  # или "file" для постоянного хранения
    volumes:
      - /opt/vsQUIC/subtrace:/var/lib/subtrace

  server:
    container_name: vsQUIC
    image: python:3.12-slim-bookworm
    labels:
      description: Implementing a WEB server to demonstrate the existing vulnerability QUIC
      name: VulnerableQuicServer
    restart: unless-stopped
    command: >
        bash -c "chmod +x /opt/startServer.sh &&
          /opt/startServer.sh"
    ports:
      - "4433:4433/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro                                       # time
      - /opt/vsQUIC/server/:/opt
    environment:
      - TZ=Europe/Moscow                                                       # time zone
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://subtrace:4317
      - OTEL_SERVICE_NAME=vsquic-server
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=demo
    depends_on:
      - subtrace
    networks:
      interaction_network:
        ipv4_address: 172.16.239.10

  client:
    container_name: haCker
    image: python:3.12-slim-bookworm
    labels:
      description: Implementing a WEB client to demonstrate the existing vulnerability QUIC
      name: QuicExploitClient
    restart: unless-stopped
    command: >
        bash -c "chmod +x /opt/startClient.sh &&
          /opt/startClient.sh"
    ports:
      - "9898:9898/tcp"
      - "9898:9898/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro                                       # time
      - /opt/vsQUIC/client/:/opt
    environment:
      - TZ=Europe/Moscow                                                       # time zone
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://subtrace:4317
      - OTEL_SERVICE_NAME=vsquic-server
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=demo
    depends_on:
      - subtrace
    networks:
      interaction_network:
        ipv4_address: 172.16.239.20

networks:
  interaction_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
