services:

  server:
    container_name: vsQUIC
    image: python:3.12-slim-bookworm
    labels:
      description: Implementing a WEB server to demonstrate the existing vulnerability QUIC
      name: VulnerableQuicServer
    restart: unless-stopped
    command: >
        bash -c "/opt/startServer.sh"
#        bash -c "python3 -m venv /opt/venv &&
#        source /opt/venv/bin/activate &&
#        pip install --upgrade pip &&
#        pip install -r /opt/requirements.txt &&
#        python /opt/quic-srv.py"
    ports:
      - "4433:4433"
    volumes:
      - /etc/localtime:/etc/localtime:ro                                       # time
      - /opt/vsQUIC/server/:/opt
    environment:
      - TZ=Europe/Moscow                                                       # time zone

  client:
    container_name: haCker
    image: python:3.12-slim-bookworm
    labels:
      description: Implementing a WEB client to demonstrate the existing vulnerability QUIC
      name: QuicExploitClient
    restart: unless-stopped
    command: >
        bash -c "/opt/startClient.sh"
#        bash -c "python3 -m venv /opt/venv &&
#        source /opt/venv/bin/activate &&
#        pip install --upgrade pip &&
#        pip install -r /opt/requirements.txt &&
#        python /opt/quic-client.py"
    ports:
      - "9898:9898"
    volumes:
      - /etc/localtime:/etc/localtime:ro                                       # time
      - /opt/vsQUIC/client/:/opt
    environment:
      - TZ=Europe/Moscow                                                       # time zone

